name: Spring Boot Build and Run on Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted  # Make sure this is your Ubuntu 22.04 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Spring Boot Application
        run: |
          nohup java -jar target/springboot-gym-html-app-github-ubuntu-1.0.1-SNAPSHOT.jar > app.log 2>&1 &
          sleep 10

      - name: Test Application Endpoint
        run: curl --fail http://localhost:9090/home.html

      - name: Success Message
        if: success()
        run: echo "Spring Boot app is running locally!"

      - name: Failure Message
        if: failure()
        run: echo "Build or run failed!"
