name: Spring Boot Build and Run on Ubuntu

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Spring Boot App (keep alive)
        env:
          RUNNER_TRACKING_ID: 0
        run: |
          nohup java -jar target/springboot-gym-html-app-github-ubuntu-1.0.1-SNAPSHOT.jar \
            --server.port=9090 > app.log 2>&1 &
          sleep 10

      - name: Test Endpoint
        run: curl --fail http://localhost:9090/home.html

      - name: Success
        if: success()
        run: echo "App is up on port 9090!"

      - name: Failure
        if: failure()
        run: echo "Build or server startup failed!"
