name: Build and Run Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Spring Boot app
        run: java -jar target/springboot-gym-html-app-github-ubuntu-1.0.0.jar

      - name: Success message
        if: success()
        run: echo " Spring Boot app is running successfully!"

      - name: Failure message
        if: failure()
        run: echo " Build or run failed!"
