name: Build and Deploy Spring Boot on Ubuntu 22.04 Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Stop existing app (if running)
      run: |
        pkill -f springboot-gym-html-app-github-ubuntu || echo "No app running"

    - name: Run Spring Boot app
      run: |
        nohup java -jar target/springboot-gym-html-app-github-ubuntu-1.0.0.jar > app.log 2>&1 &
